name: Test action

on:
  push:
    branches:
      - 'master'
      - 'feature/add-cleanup-actions'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: Test GitHub action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: tag hello world image
        run: docker tag hello-world:latest ghcr.io/nodefactoryio/github-packages-cleanup-sample:${{github.sha}}
      - name: push hello world image
        run: docker push ghcr.io/nodefactoryio/github-packages-cleanup-sample:${{github.sha}}
      - name: Run cleanup action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package_name: github-packages-cleanup-sample
          num_versions_to_keep: 1
